### PR TITLE
bump pandas version, fix windows specific errors

### PR DESCRIPTION
**Pull request by brubsby**
not 100% sure the timeout function changes are completely portable, let me know if you have any problems with them. but it seems to be working correctly otherwise! and sorry about the rearranging of the imports, pycharm got a little carried away

### CODE REVIEW

**Comment by brubsby** [comment]
not sure what's going on in Merge branch 'dev' into dev here.

**Comment by brubsby** [comment]
I think I see what happened but not sure how to fix it, i'll put off trying to fix it until you respond at all (I think you're probably just in "solo dev not checking github mode" and just pushing changes from your machine, which is fine)

**Comment by thiswillbeyourgithub** [comment]
Thanks a lot for the interest! You just happened to arrive at a very bad time where I'm switching hardware and had an issue with threads left hanging so I'm switching to joblib to allow properly disabling threading. And I did an errand by switching from argparse to fire.

I won't dive into your changes before fixing my stupid joblib mistakes so hang in there (pun intended)

**Comment by thiswillbeyourgithub** [comment]
I think it would be best if you closed this PR and do another clean one as my dev changes  are screwing up the diffs. If you don't mind. Except if tour git-savvy enough to clean this oneup but I'm not :)

**Comment by thiswillbeyourgithub** [comment]
Also I would prefer having separate commits for the pandas fix and the timeout fix as pandas compatiboloty was a huge pain for me in the past

**Comment by brubsby** [comment]
no worries! I'll probably just try to remake my changes on a fresh fork once things are marginally stabilized. let me know when it would be good!

**Comment by thiswillbeyourgithub** [comment]
Developpment is hectic but tomorow should be good. I don't recommend investing too much time on code change and instead smaller PRs.

If yyou have questions don't hesitate, few people laid their eyes on this code and i know there are tons  of questionnable design choices.

My goal is still to make it noob friendly in about 12month when I finished med schood. Recently I did some spaghetti code for some features I needed, notably the bypass argument that I use to crrate one single deck

**Comment by thiswillbeyourgithub** [comment]
I haven't heard of you so I'm closing this in the meantime.

**Pull request closed without merging**
